spring:
  datasource:
    url: jdbc:h2:mem:shop;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # na rekrutacj? OK (tworzy schemat JPA)
    properties:
      hibernate.format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true


